# Generated by Django 3.0.6 on 2025-01-18 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='12345', max_length=128, verbose_name='password')),
                ('registration_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='user first name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='user last name')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='user mobile number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('reader', 'Reader')], default='reader', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('login_created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('login_update_timestamp', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users')),
            ],
        ),
    ]
